name: TempBanNew
version: '1.0'
main: plugins.tempbannew.TempBanNew
api-version: '1.19'
commands:
  tempban:
    description: ban player

  reloadconfig:
    description: reloads config
  unban:
    description: unbans player